### ISSUE TITLE
Cannot build with QtCreator

### ISSUE THREAD

**Issue by acestronautical** [ynonp/Pong#1]
Trying to build using QtCreater with QT 5.6 results in error:
 "C:\Users\Lappy\Downloads\Pong-master\main.cpp:1: error: QtGui/QApplication: No such file or directory
 #include <QtGui/QApplication>
                              ^"

**Comment by Thirsk** [comment]
Add `QT += widgets` to Pong.pro then run qmake (Build>Run qmake)
Then change it from `#include <QtGui/QApplication>` to just `#include <QApplication>`
